sample_sap:
  vars:
    ansible_user: cloud-user
  children:
    hanas:
      hosts:
        #Yes, yes, should be using group_vars
        # tower project did not, and am changing as little as possible, first pass
        hana-48jll1.example.com: # SAMPLE: CHANGE ME
            storage_pools:
                - name: sap
                  disks:
                    - sdb
                  volumes:
                    - name: data
                      size: "128 GiB"
                      mount_point: "/hana/data"
                      state: present
                    - name: log
                      size: "64 GiB"
                      mount_point: "/hana/log"
                      state: present
                    - name: shared
                      size: "256 GiB"
                      mount_point: "/hana/shared"
                      state: present
                    - name: sap
                      size: "50 GiB"
                      mount_point: "/usr/sap"
                      state: present
            sap_hana_deployment_bundle_path: /software/HANA_installation
            sap_hana_deployment_bundle_sar_file_name: IMDB_SERVER20_046_0-80002031.SAR
            sap_hana_deployment_sapcar_path: /software/SAPCAR
            sap_hana_deployment_sapcar_file_name: SAPCAR_1311-80000935.EXE
            sap_hana_deployment_root_password: "R3dh4t123!"
            sap_hana_deployment_sapadm_password: "R3dh4t123!"
            sap_hana_deployment_hana_sid: RHE
            sap_hana_deployment_hana_instance_number: "00"
            sap_hana_deployment_hana_env_type: development
            sap_hana_deployment_hana_mem_restrict: "n"
            sap_hana_deployment_common_master_password: "R3dh4t123!"
            sap_hana_deployment_sidadm_password: "R3dh4t123!"
            sap_hana_deployment_hana_db_system_password: "R3dh4t123!"
            sap_hana_deployment_ase_user_password: "R3dh4t123!"
            sap_hana_deployment_apply_license: false
            sap_hana_hsr_hana_sid: "RHE"
            sap_hana_hsr_hana_instance_number: "00"
            sap_hana_hsr_hana_db_system_password: "R3dh4t123!"
            sap_hana_hsr_hana_primary_hostname: "hana-48jll1" # SAMPLE: CHANGE ME
            sap_hana_hsr_full_primary_hostname: "hana-48jll1" # SAMPLE: CHANGE ME
            sap_hana_hsr_full_secondary_hostname: "hana-48jll2" # SAMPLE: CHANGE ME
            sap_hana_hsr_role: "primary"
            sap_hana_hsr_alias: "DC1"
        hana-48jll2.example.com: # SAMPLE: CHANGE ME
            storage_pools:
            - name: sap
              disks:
                - sdb
              volumes:
                - name: data
                  size: "128 GiB"
                  mount_point: "/hana/data"
                  state: present
                - name: log
                  size: "64 GiB"
                  mount_point: "/hana/log"
                  state: present
                - name: shared
                  size: "256 GiB"
                  mount_point: "/hana/shared"
                  state: present
                - name: sap
                  size: "50 GiB"
                  mount_point: "/usr/sap"
                  state: present
            sap_hana_deployment_bundle_path: /software/HANA_installation
            sap_hana_deployment_bundle_sar_file_name: IMDB_SERVER20_046_0-80002031.SAR
            sap_hana_deployment_sapcar_path: /software/SAPCAR
            sap_hana_deployment_sapcar_file_name: SAPCAR_1311-80000935.EXE
            sap_hana_deployment_root_password: "R3dh4t123!"
            sap_hana_deployment_sapadm_password: "R3dh4t123!"
            sap_hana_deployment_hana_sid: RHE
            sap_hana_deployment_hana_instance_number: "00"
            sap_hana_deployment_hana_env_type: development
            sap_hana_deployment_hana_mem_restrict: "n"
            sap_hana_deployment_common_master_password: "R3dh4t123!"
            sap_hana_deployment_sidadm_password: "R3dh4t123!"
            sap_hana_deployment_hana_db_system_password: "R3dh4t123!"
            sap_hana_deployment_ase_user_password: "R3dh4t123!"
            sap_hana_deployment_apply_license: false
            sap_hana_hsr_hana_sid: "RHE"
            sap_hana_hsr_hana_instance_number: "00"
            sap_hana_hsr_hana_db_system_password: "R3dh4t123!"
            sap_hana_hsr_hana_primary_hostname: "hana-48jll1" # SAMPLE: CHANGE ME
            sap_hana_hsr_full_primary_hostname: "hana-48jll1" # SAMPLE: CHANGE ME
            sap_hana_hsr_full_secondary_hostname: "hana-48jll2" # SAMPLE: CHANGE ME 
            sap_hana_hsr_role: "secondary"
            sap_hana_hsr_alias: "DC2"
    s4hanas:
      hosts:
        s4hana-48jll.example.com: # SAMPLE: CHANGE ME
            storage_pools:
            - name: sap
              disks:
                - sdb
              volumes:
                - name: sap
                  size: "50 GiB"
                  mount_point: "/usr/sap"
                  state: present
                - name: sapmnt
                  size: "20 GiB"
                  mount_point: "/usr/sapmnt"
                  state: present
                - name: swap
                  size: "20 GiB"
                  state: present

            sap_s4hana_deployment_product_id: "NW_ABAP_OneHost:S4HANA1909.CORE.HDB.ABAP"
            sap_s4hana_deployment_sapcar_path: "/software/SAPCAR"
            sap_s4hana_deployment_sapcar_file_name: "SAPCAR_1311-80000935.EXE"
            sap_s4hana_deployment_swpm_path: "/software/S4HANA_installation"
            sap_s4hana_deployment_swpm_sar_file_name: "SWPM20SP04_6-80003424.SAR"
            sap_s4hana_deployment_db_schema_password: "R3dh4t123!"
            sap_s4hana_deployment_db_schema_abap_password: "R3dh4t123!"
            sap_s4hana_deployment_master_password: "R3dh4t123!"
            sap_s4hana_deployment_hana_systemdb_password: "R3dh4t123!"
            sap_s4hana_deployment_sid: "RHE"
            sap_s4hana_deployment_db_host: "hana-48jll1"  # SAMPLE: CHANGE ME (ALSO TODO: USE VIP)
            sap_s4hana_deployment_db_sid: "RHE"
            sap_s4hana_deployment_hana_instance_nr: "00"
            sap_s4hana_deployment_hana_system_password: "R3dh4t123!"
            sap_s4hana_deployment_parallel_jobs_nr: "30"
            sap_s4hana_deployment_db_sidadm_password: "R3dh4t123!"
            sap_s4hana_deployment_igs_path: "/software/S4HANA_installation"
            sap_s4hana_deployment_igs_file_name: "igsexe_9-80003187.sar"
            sap_s4hana_deployment_igs_helper_path: "/software/S4HANA_installation"
            sap_s4hana_deployment_igs_helper_file_name: "igshelper_17-10010245.sar"
            sap_s4hana_deployment_kernel_dependent_path: "/software/S4HANA_installation"
            sap_s4hana_deployment_kernel_dependent_file_name: "SAPEXEDB_201-80003385.SAR"
            sap_s4hana_deployment_kernel_independent_path: "/software/S4HANA_installation"
            sap_s4hana_deployment_kernel_independent_file_name: "SAPEXE_201-80003386.SAR"
            sap_s4hana_deployment_software_path: "/software/S4HANA_installation"
            sap_s4hana_deployment_sapadm_password: "R3dh4t123!"
            sap_s4hana_deployment_sap_sidadm_password: "R3dh4t123!"
